version: '3'

services:
  fpm:
    build:
      context: ./fpm
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: app_fpm
    restart: always
    volumes:
      - ./data:/home/serveruser/data:delegated
    networks:
      app_net:
networks:
  app_net:
